### ISSUE TITLE
while starting console,command 'npm start' throws following error

### ISSUE THREAD

**Issue by niteshsabankar** [trustedanalytics/console#2]
root@tap:~/tools/console# npm start

> console@0.4.151 start /root/tools/console
> node app/server/server.js

/root/tools/console/app/server/auth/oauth2.js:23
    authorizationURL: sso.authorizationUri,
                         ^
TypeError: Cannot read property 'authorizationUri' of undefined
    at Object.<anonymous> (/root/tools/console/app/server/auth/oauth2.js:23:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/tools/console/app/server/auth/auth.js:18:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! console@0.4.151 start: `node app/server/server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the console@0.4.151 start script.
npm ERR! This is most likely a problem with the console package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app/server/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls console
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-51-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /root/tools/console
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/tools/console/npm-debug.log
npm ERR! not ok code 0

**Comment by szymonbultrowicz** [comment]
Hi. It seems that you didn't set the VCAP_SERVICES environment properly (see: https://github.com/trustedanalytics/console#setting-up-dependencies). Console is trying to read "authorizationUri" of a service which hasn't been found in the configuration.
